title: "Paul M Furley, developer"
gems:
  - jekyll-redirect-from
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog_post"
      author: "Paul M Furley"

permalink: /:title
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Dockerfile
  - Makefile
